### ISSUE TITLE
Investigate and fix failing e2e tests

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-app#2009]
The e2e tests failed the evening of 6/19\. They had run without error the prior evening (6/18) and no merges into the develop branch occurred between the runs with infers that there is a timeout issue occurring. Rerunning the e2e tests manually did not result in a clean run.

[![](https://github.com/fecgov/fecfile-web-app/assets/2971785/ac42a090-f3e7-4d7e-a6e6-824c490393bb)](https://github.com/fecgov/fecfile-web-app/assets/2971785/ac42a090-f3e7-4d7e-a6e6-824c490393bb)

[![](https://github.com/fecgov/fecfile-web-app/assets/2971785/ac42a090-f3e7-4d7e-a6e6-824c490393bb)](https://github.com/fecgov/fecfile-web-app/assets/2971785/ac42a090-f3e7-4d7e-a6e6-824c490393bb)

Acceptance Criteria

**Given** nightly e2e tests run **Then** run without any failing tests

### QA Notes ###

 DEV Notes
Error from log:

 ```
 Running:  F24/reports-f24-independent-expenditures.cy.ts                                 (4 of 13)


  Form 24 Independent Expenditures
    1) Independent Expenditures created on a Form 24 should be linked to a Form 3X


  0 passing (3m)
  1 failing

  1) Form 24 Independent Expenditures
       Independent Expenditures created on a Form 24 should be linked to a Form 3X:
     CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element is not visible:

`...`

This element `` is not visible because its parent `` has CSS property: `display: none`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at runVisibilityCheck (http://*********:4200/__cypress/runner/cypress_runner.js:144890:58)
      at Object.isStrictlyVisible (http://*********:4200/__cypress/runner/cypress_runner.js:144904:10)
      at runAllChecks (http://*********:4200/__cypress/runner/cypress_runner.js:112784:26)
      at retryActionability (http://*********:4200/__cypress/runner/cypress_runner.js:112852:16)
      at tryCatcher (http://*********:4200/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://*********:4200/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://*********:4200/__cypress/runner/cypress_runner.js:143678:68)
      at  (http://*********:4200/__cypress/runner/cypress_runner.js:143619:14)
      at tryCatcher (http://*********:4200/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://*********:4200/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://*********:4200/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://*********:4200/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://*********:4200/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://*********:4200/__cypress/runner/cypress_runner.js:1645:18)
      at  (http://*********:4200/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at ReportListPage.clickCreateAndSelectForm (webpack://fec-e-file/./cypress/e2e/pages/reportListPage.ts:12:0)
      at ReportListPage.createF24 (webpack://fec-e-file/./cypress/e2e/pages/reportListPage.ts:62:0)
      at F24Setup (webpack://fec-e-file/./cypress/e2e/F24/f24-setup.ts:14:18)
      at Context.eval (webpack://fec-e-file/./cypress/e2e/F24/reports-f24-independent-expenditures.cy.ts:24:16)
```

### DEV Notes ###

null

### Design ###

null

[FECFILE-1433](https://fecgov.atlassian.net/browse/FECFILE-1433)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

Passing e2e tests:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/5997/workflows/bd703e4d-6827-437d-8ae2-2f37dc17e05a/jobs/20685


![Image](https://github.com/fecgov/fecfile-web-app/assets/2971785/59f0b7fe-6d5d-40f6-91f4-d7ea357bc62e)
